coverage:
  status:
    project:
      default:
        # 프로젝트 커버리지 상태 기본 설정
        target: auto # 목표 커버리지 자동 설정
        threshold: 0% # 허용 가능한 최소 커버리지 변경
        base: auto # 기준 커밋 자동 설정
        informational: true # 초기에는 정보 제공 목적으로만 사용
    patch:
      default:
        informational: true # 패치 커버리지도 초기에는 정보 제공 목적으로만 사용

comment:
  layout: 'diff, flags, files' # PR에 보여줄 커버리지 정보 형식
  behavior: default
  require_changes: false # 커버리지 변경이 없더라도 댓글 작성
  require_base: false # 기본 보고서가 없어도 댓글 작성 가능
  require_head: true # 헤드 보고서는 반드시 필요
  hide_project_coverage: false # 전체 커버리지 정보를 숨기지 않음
