##
version: 2.1

orbs:
  cypress: cypress-io/cypress@3

workflows:
  cypress-tests:
    jobs:
      - cypress/run:
          browser: chrome
          start-command: npm run start
          wait-on: 'http://localhost:3000'
